mozilla-l10n/localizer-documentation

SUMMARY.md
products/l10n_testing.md
tools/pontoon/resources.md
webprojects/README.md
webprojects/amo.md

Opening on behalf of @peiying2

(Fixes issue 18) Add AMO documentation

---

SUMMARY.md
products/l10n_testing.md
webprojects/README.md
webprojects/SUMO.md
webprojects/amo.md

I did not provide detailed testing setup from the dev page but linked to it in case people wants to do local testing.
I will need to get more clarity from Vesper on local testing, and how soon the strings can be updated through Pontoon, github or both instantaneously.  I should be able to update that in the morning.

add file SUMO and SUMO entries to other files

---

misc/l10n_feedback.md

First draft of giving feedback in issue 4 https://github.com/mozilla-l10n/localizer-documentation/issues/4

Document on reviewing someone else's translations

---

products/firefox_ios/testing.md
products/focus/testing_focus.md

Updated screenshot links and some outdated info

---

book.json
products/firefox_desktop/testing.md

Also minitor updates to Firefox desktop doc

(fix issue #17) Add link to l10n build docs

---

webprojects/amo.md

Fixing link to AMO-frontend

---

tools/fluent/basic_syntax.md

https://github.com/projectfluent/fluent/pull/112

[Fluent] Use variable instead of external argument

---

community/l10n_community_roles.md

New l10n-drivers section & expanded Implementation section

---

src/webprojects/sumo.md

- Update create account info/fix the link
- Update contact info
- Remove IRC, replace with Discourse
- Fix formatting error of hyperlinked text

SUMO: fix issue #151

---

src/products/firefox_ios/adding_new_ios_locale.md
src/products/focus/testing_focus.md

Should fix https://github.com/mozilla-l10n/localizer-documentation/issues/149

Fix links and update mobile docs

---

src/products/firefox_ios/testing.md

Updated testing instructions

---

src/products/mozilla_org/testing.md

- add Fluent related test instruction.
- update sync and activation information
- add change request to legacy pages
- update dynamic page file names

Update mozorg testing instruction

---

src/SUMMARY.md
src/webprojects/README.md
src/webprojects/fxa.md

- Doc creation
- Update Readme.md
- Update Summary.md

FxA: setup the doc

---

src/misc/bugzilla_l10n.md
src/products/firefox_android/how_to_localize.md
src/products/firefox_android/testing.md

Waiting until Elmo is actually shut down.

Remove references to Elmo

---

src/products/firefox_android/how_to_localize.md
src/products/firefox_android/testing.md

Updated firefox android docs

---

src/tools/pontoon/translate.md

Updated url for Downloading translation memory (.tmx) files via command line

This  will resolve issue #185

---

src/products/mozilla_org/testing.md

Remove content about .lang which is no longer relevent.

Remove reference to .lang

---

src/products/firefox_ios/testing.md

Do we really need a review in case of such minor changes?

Updating minimum OS version for testing iOS

---

src/tools/pontoon/workflow.md

Pontoon update: workflow.md

---

src/products/mozilla_org/testing.md
src/webprojects/sumo.md

- SUMO.md: removed the discourse entry per Tasos feedback.
- Revise mozilla.org.

Modify mozilla.org testing doc; Update SuMo test doc

---

src/tools/pontoon/notifications.md

Part of https://github.com/mozilla/pontoon/issues/3469
See related PR: https://github.com/mozilla/pontoon/pull/3541

Change recipient list for translation comment notifications

---

src/SUMMARY.md
src/products/firefox_ios/README.md
src/products/firefox_ios/adding_new_ios_locale.md
src/products/firefox_ios/testing.md

fixes #265 
EDIT: not sure this entirely fixes the issue I linked, there may be other areas still left to clean up in other projects. Let me know and I'll unlink the issue before this gets merged

Linked to existing documentation

---

src/products/firefox_ios/testing.md

Fixes #268 
Considering dropping the first paragraph as we don't announce these things on Discourse anymore (maybe better to send to our localization blog or Matrix)

Adds details to new screenshots releases, and some fixes
